title: My Blog
author: zack785
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Really great and accurate description for my website

# social links
twitter_username: zack785
github_username:  zack785

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
